### PR TITLE
Update WG Green Reviews Leads and TAG TL

### PR DESCRIPTION
**Pull request by leonardpahlke**
The TAG Environmental Sustainability voted new contributors into Tech Lead & Chair roles. This PR updates access accordingly. 

* @guidemetothemoon was voted into a CNCF TAG ENV TL role https://lists.cncf.io/g/cncf-toc/topic/nomination_of_kristina/102766241. 
* @AntonioDiTuri was voted into a CNCF TAG ENV WG Green Reviews Chair role https://github.com/cncf/tag-env-sustainability/issues/293.
* @rossf7 was voted into a CNCF TAG ENV WG Green Reviews TL role https://github.com/cncf/tag-env-sustainability/issues/292. 

Note: This PR is currently in draft mode and will be opened after @guidemetothemoon was approved 🤞. 

fyi @RobertKielty

### CODE REVIEW

**Comment by leonardpahlke** [comment]
@RobertKielty could we invite Niki into the org so the validation passes?

**Comment by RobertKielty** [comment]
Hi @leonardpahlke I've sent out an invite to @nikimanoledaki who is now a cncf-tags member. 

I'll merge this after the validation passes.

**Comment by RobertKielty** [comment]
I also sent out an invite to @guidemetothemoon

**Comment by leonardpahlke** [comment]
Thanks Rob 🙌

**Comment by tegioz** [comment]
Please note that CLOWarden won't try to validate this PR again unless there is some more activity on it (i.e. new commit). It looks like the invitations were accepted, so another option would be to merge it as is given that the error raised has been solved.

**Comment by rossf7** [comment]
@RobertKielty Could this be merged?  As per the suggestion from @tegioz https://github.com/cncf-tags/org-admin/pull/11#issuecomment-1858111083

It would help me and @AntonioDiTuri a lot to be able to add assignees and labels in our tooling repo.

cc @leonardpahlke

**Comment by leonardpahlke** [comment]
I open a new PR. To fix this one.

**Pull request closed without merging**
