### PR TITLE
Add CDI Rust team and add them to CDI-rs

### PR DESCRIPTION
**Pull request by zvonkok**
Add CDI Rust team and ass them to CDI-rs

### CODE REVIEW

**Comment by zvonkok** [comment]
cc @RobertKielty

**Review by elezar — CHANGES_REQUESTED** [review]
Could we add the users for the "regular" CDI repo to this team as well?

**Comment by zvonkok** [comment]
You mean adding; 
```
  - bart0sh
  - elezar
  - kad
  - klihub
  - klueska
   - marquiz
 ``` 
as members additionallly ?

**Comment by RobertKielty** [comment]
@zvonkok Should I merge this now as-is?

**Comment by elezar** [comment]
> You mean adding;
> 
> ```
>   - bart0sh
>   - elezar
>   - kad
>   - klihub
>   - klueska
>    - marquiz
> ```
> 
> as members additionallly ?

Yes. The intention is to include active members of the cod org for the purposes of adding testing etc. for the rust implementation.

**Comment by elezar** [comment]
@RobertKielty feel free to merge as is. We can always update the list after the fact.

**Pull request merged**
